$ANSIBLE_VAULT;1.1;AES256
37343136626630643037646131666234623230343735633736323038353138613038306363653437
3839346162346465666466383362396337323762343365660a346233366134616161316464313965
39346164623236333766383561633535623333313535616138383138653433363237333531313363
3131396562643465650a396663323361336635663635653763613833343835336562333539616339
61373666656339626630343062613434376434346462383531353662663533343839376539636136
33666631613136663138383330643938383161663134333066396339326166386634343632396165
39653736623035323433616133633464336537303464356539336634326561323930313731323438
35333637313463646661646261333961353231663830356161393431623562376664666634303035
62366431353066356235653366653336366537323935663332626635316162636436636561653430
34653236386466343432373931626131336566613261313262333332323230343539386233316438
61653264663334326531663261316436343531373966663635613933356537343839653635366366
62633565356136653130316233646361343630613736356165633535303838323064333537346537
31313336313432623335333463363433616635303731326265363131316265353938326461356638
37623366663236383336323830363837643063353735653337616335353165663734326564356634
346563383730356530656364393665353033
